kind: Deployment
apiVersion: apps/v1
metadata:
  name: apigo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apigo
    spec:
      containers:
        - name: apigo
          image: >-
            quay-enterprise-quay-quay-enterprise.apps.ocppaz0.ar.bsch/a309788/apigo:1
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: apigo
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: apigo
  type: ClusterIP
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: apigo
spec:
  host: apigo.apps.ocplab.ar.bsch
  to:
    kind: Service
    name: apigo
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
